### ISSUE TITLE
Error 65539 

### ISSUE THREAD

**Issue by peterADM** [AllTheMods/ATM-5#114] opened 2020-05-09 20:19 UTC
i keep getting the error 65539 even tho i have my latest game driver

## Expected Behavior
lauch the game

## Current Behavior
get the error 65539

## Steps to Reproduce

1.
2.
3.
4.

**Comment by whatthedrunk** [comment] 2020-05-12 15:32
Duplicate of #32 check there for a workaround.

**Closed as completed by whatthedrunk** 2020-05-12 15:32 UTC
