### ISSUE TITLE
Is the Kappa Pickaxe bugged?

### ISSUE THREAD

**Issue by Aquabrodie** [AllTheMods/ATM-5#174] opened 2020-06-19 13:50 UTC
## Expected Behavior
I can't find any information online about it but I would think a pickaxe made with 2 iron, 1 brick and 2 sticks shouldn't be doing 31516 attack damage.

## Current Behavior
Doing an insane amount of damage, maybe its meant to kill me when used? thats what I thought it would do but currently I'm able to use it with no downsides.

## Steps to Reproduce
1. Craft Kappa Pickaxe
2. Hit a mob with a lot of health, for example I hit the wither and it got oneshot, which probably shouldn't happen.

## Detailed Description
A pickaxe thats super easy to craft and use, also has an insane amount of durability and attack damage. Not sure if this is intended to function like this since there doesn't seem to be anything online about this item.

**Comment by Salamance73** [comment] 2020-06-22 02:06
This is expected behavior lol, the name is based off the Kappa emote and its connotation of being a 
"just kidding" emote.

**Comment by whatthedrunk** [comment] 2020-06-22 13:57
Duplicate of https://github.com/AllTheMods/ATM-5/issues/171

**Closed as completed by whatthedrunk** 2020-06-22 13:57 UTC
