### ISSUE TITLE
ComputerCraft crashes game

### ISSUE THREAD

**Issue by vidiot5533** [AllTheMods/ATM-5#137] opened 2020-05-24 04:36 UTC
This is actually a cascade of bugs which I came across. The titular bug is the third one, but I only came across it because I ran into two other bugs first.

So the list of bugs are as follows:
Bug number 1: Was creating a short redstone circuit. and needed a constant. Go-to is usually an item frame for numbers 1-7. No output was given behind the item frame regardless of orientation, which is unusual considering that's a vanilla minecraft feature. Not sure why that's happening.

Bug number 2: Tried to use RFTools' Analog block to set the output to a constant, it refused to output anything other than the input regardless of the gui settings. I suspect if there's something messing with vanilla redstone behavior, it may also be affecting RFTools. can't confirm.

Bug number 3: Tried to use a CC program to run the circuit instead. Placing the block crashed my game. Suspect an incompatibility between a mod by Silent and CC due to crash report info. Something that was updated in the last week caused this crash, as my old creative world was deleted due to it crashing and it had CC terminals as well, it worked last week. Crash report below:
[crash-2020-05-23_21.01.28-server.txt](https://github.com/AllTheMods/ATM-5/files/4672947/crash-2020-05-23_21.01.28-server.txt)

**Comment by OfficialStamper** [comment] 2020-05-25 21:31
No. 3 : This is a duplicate of #126

**Comment by whatthedrunk** [comment] 2020-05-26 18:25
Closing this issue and keeping 126 open till we verify if its fixed.

**Closed as completed by whatthedrunk** 2020-05-26 18:25 UTC
