### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by pixartist** [AllTheMods/ATM-5#20] opened 2020-02-09 13:31 UTC
When trying to start the server I am getting the following errors (5-1.2):

`[14:29:44] [Server thread/INFO] [ne.mi.fm.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.210  [14:29:44] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found [14:29:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Apotheosis (apotheosis) encountered an error during the common_setup event phase
§7java.lang.IllegalAccessException: Can not set final net.minecraft.world.gen.blockstateprovider.BlockStateProvider field net.minecraft.world.gen.feature.BlockClusterFeatureConfig.field_227289_a_ to net.minecraft.world.gen.blockstateprovider.SimpleBlockStateProvider
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}                at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
[14:29:44] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/minecraft/server/./crash-reports/crash-2020-02-09_14.29.44-server.txt
[14:29:44] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[14:29:44] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[14:29:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:185) ~[?:?] {re:classloading}              at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1002) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:534) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:566) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:549) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:674) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}`

**Comment by Quu1337** [comment] 2020-02-10 10:42
this was caused by apotheosis not liking openjdk. was fixed on discord.

**Closed** 2020-02-13 03:29 UTC
